### ISSUE TITLE
adb shell 报错连接不上设备

### ISSUE THREAD

**Issue by sunfengqi8023** [cxplan/CXTouch#8]
Exception in thread "main" java.lang.RuntimeException: 远程主机强迫关闭了一个现有的连接。
	at com.cxplan.projection.core.adb.AdbUtil.shell(AdbUtil.java:189)
	at com.cxplan.projection.core.adb.AdbUtil.shell(AdbUtil.java:172)
	at com.cxplan.projection.core.adb.AdbUtil.getDeviceIp(AdbUtil.java:269)
	at com.android.ddmlib.CXAdbHelper.main(CXAdbHelper.java:179)
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:759)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:736)
	at com.android.ddmlib.AdbHelper.readAdbResponse(AdbHelper.java:222)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:456)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:617)
	at com.cxplan.projection.core.adb.AdbUtil.shell(AdbUtil.java:187)
	... 3 more

**Comment by sunfengqi8023** [comment]
注释掉 重复调用的getDeviceIp方法解决
