### ISSUE TITLE
does not respond to keyevents

### ISSUE THREAD

**Issue by holy834** [cxplan/CXTouch#9]
Connection is okay and latency is awesome. It also supports mouse and navigation events. However keyevents doesn't work.

logcat shows warning when pressing keys:
W/BroadcastQueue: Unable to launch app com.cxplan.projection.mediate/10199 for broadcast Intent { act=COM.CXPLAN.TOUCH.INPUTER flg=0x10 cmp=com.cxplan.projection.mediate/.inputer.InputerReceiver (has extras) }: process is bad

CXmediate app also fail with:
E/AndroidRuntime: FATAL EXCEPTION: Connect Thread
    Process: com.cxplan.projection.mediate, PID: 711
    java.lang.RuntimeException: Connecting to message server is timeout: forward port=2014
        at com.cxplan.projection.mediate.inputer.CXTouchIME$1.run(CXTouchIME.java:164)
        at java.lang.Thread.run(Thread.java:760)

**Comment by holy834** [comment]
Not an issue, my fault. The app must have network permission.
